version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: forecast
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/forecast
      POLL_INTERVAL: 60 # default to 60 minutes
    ports:
      - "5001:5001"
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  pgdata:
